### ISSUE TITLE
Out of stock message shown after add-to-cart disabled

### ISSUE THREAD

**Issue by donniesg** [sbodak/magento2-b2b-disable-add-to-cart-button-for-guest#2]
I am using this module in my Magento 2.2.5 installation. When I disable the button, strangely, the button did go away but the product is now marked as out of stock in the category page. Have anyone else encountered this problem?

**Comment by sbodak** [comment]
@donniesg It's because of using the plugin on `isSalable` method.

It's a good approach because it secures to add a product also from API / different places.

You can modify the product template to change a view:

```
<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
    <?php if ($_product->isSaleable()): ?>
        <!-- here is an Add to Cart code -->
    <?php else: ?>
        <?php if ($_product->isAvailable()): ?>
            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
        <?php else: ?>
            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
        <?php endif; ?>
    <?php endif; ?>
</div>
```
