### ISSUE TITLE
Magento 2.3 support?

### ISSUE THREAD

**Issue by epiblue** [sbodak/magento2-b2b-disable-add-to-cart-button-for-guest#3]
Have you tested it on 2.3? I've installed it, but it seems that it doesn't work? Thank you!

**Comment by sbodak** [comment]
@epiblue I will do.

**Comment by sbodak** [comment]
@epiblue I just tested it on fresh Magento 2.3 and it works correctly.

Probably, you didn't enable it in the admin panel.
